import type { Metadata } from "next";
import { geistMono, inter, satoshi } from "@/styles/fonts";
import "@/styles/globals.css";
import RootProviders from "./providers";
import { cn } from "@/lib/utils";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className={cn(satoshi.variable, inter.variable, geistMono.variable)}>
      <body>
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
